# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 11a748d729c90befa765f9964e9a9748cb7bd242518c1c80877fae63c03daae63966abb69e12545ba191d21426c54a512647e3344194457952b596cdab7d5b32

test:
  secret_key_base: 115fb2e8e99166c980bb3a4f9b6918bbbdf46b11787bf58554257522db8fd738700fb39cf3ea606a221bc99c80302e89c5c893d5ce484cf2860a34f26bd3ec81

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
